### ISSUE TITLE
Cannot find name 'CheckoutRequest'.ts(2304)

### ISSUE THREAD

**Issue by prabhashibuddhima** [nipuna21018/cordova-plugin-payhere#1]
Hi,

when I try to implement Payhere to my ionic app, I got an error called **Cannot find name 'CheckoutRequest'.ts(2304)**

![image](https://user-images.githubusercontent.com/29029785/87026320-6f00db80-c190-11ea-909d-464840c5e3ca.png)

can you help me with it?

**Comment by nipuna21018** [comment]
Hi,

Try with npm install types-payhere --save

After installing above package, resolve the imports

 Error will be resolved with above fix

**Comment by prabhashibuddhima** [comment]
already done it. but no luck

**Comment by nipuna21018** [comment]
Add this import
import { PayHere,CheckoutRequest } from "types-payhere/ngx";

**Comment by prabhashibuddhima** [comment]
thanks a lot for the support!
